

*
* Visual Studio Code Server
*
* Reminder: You may only use this software with Visual Studio family products,
* as described in the license https://aka.ms/vscode-remote/license
*

Extension host agent listening on 33857

[09:47:26] Extension host agent started.
[09:47:26] [127.0.0.1][f06d6040][ManagementConnection] New connection established.
[09:47:26] [127.0.0.1][85d742d3][ExtensionHostConnection] New connection established.
[09:47:26] [127.0.0.1][85d742d3][ExtensionHostConnection] <1570> Launched Extension Host Process.
[09:47:33] [127.0.0.1][f06d6040][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[09:47:33] [127.0.0.1][85d742d3][ExtensionHostConnection] <1570> Extension Host Process exited with code: 0, signal: null.
Last EH closed, waiting before shutting down
[09:47:33] Last EH closed, waiting before shutting down
Got delay-shutdown request while in shutdown timeout, delaying
[09:47:37] Got delay-shutdown request while in shutdown timeout, delaying
Cancelling previous shutdown timeout
[09:47:37] Cancelling previous shutdown timeout
[09:47:37] [127.0.0.1][888840af][ManagementConnection] New connection established.
[09:47:37] [127.0.0.1][ec1ce769][ExtensionHostConnection] New connection established.
[09:47:37] [127.0.0.1][ec1ce769][ExtensionHostConnection] <1761> Launched Extension Host Process.
rejected promise not handled within 1 second: Error: Could not find pty with id "5"
stack trace: Error: Could not find pty with id "5",    at r._throwIfNoPty (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:17:5354),    at r.updateTitle (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:17:1694),    at Object.call (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:13:8364),    at L.onPromise (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:12:4938),    at L.onRawMessage (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:12:4297),    at /home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:12:3553,    at D.fire (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:8:1712),    at process.N (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:6:33914),    at process.emit (events.js:315:20),    at emit (internal/child_process.js:903:12),    at processTicksAndRejections (internal/process/task_queues.js:81:21)
[Error: Could not find pty with id "5",    at r._throwIfNoPty (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:17:5354),    at r.updateTitle (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:17:1694),    at Object.call (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:13:8364),    at L.onPromise (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:12:4938),    at L.onRawMessage (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:12:4297),    at /home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:12:3553,    at D.fire (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:8:1712),    at process.N (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:6:33914),    at process.emit (events.js:315:20),    at emit (internal/child_process.js:903:12),    at processTicksAndRejections (internal/process/task_queues.js:81:21)]
[09:47:55] [127.0.0.1][888840af][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[09:47:55] [127.0.0.1][ec1ce769][ExtensionHostConnection] <1761> Extension Host Process exited with code: 0, signal: null.
Cancelling previous shutdown timeout
[09:47:55] Cancelling previous shutdown timeout
Last EH closed, waiting before shutting down
[09:47:55] Last EH closed, waiting before shutting down
Got delay-shutdown request while in shutdown timeout, delaying
[09:48:00] Got delay-shutdown request while in shutdown timeout, delaying
Cancelling previous shutdown timeout
[09:48:00] Cancelling previous shutdown timeout
[09:48:00] [127.0.0.1][c34691fe][ManagementConnection] New connection established.
[09:48:00] [127.0.0.1][8f535975][ExtensionHostConnection] New connection established.
[09:48:00] [127.0.0.1][8f535975][ExtensionHostConnection] <1933> Launched Extension Host Process.
[09:52:18] [127.0.0.1][c34691fe][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[09:52:18] [127.0.0.1][8f535975][ExtensionHostConnection] <1933> Extension Host Process exited with code: 0, signal: null.
Cancelling previous shutdown timeout
[09:52:18] Cancelling previous shutdown timeout
Last EH closed, waiting before shutting down
[09:52:18] Last EH closed, waiting before shutting down
Got delay-shutdown request while in shutdown timeout, delaying
[09:52:22] Got delay-shutdown request while in shutdown timeout, delaying
Cancelling previous shutdown timeout
[09:52:22] Cancelling previous shutdown timeout
[09:52:23] [127.0.0.1][2526b347][ManagementConnection] New connection established.
[09:52:23] [127.0.0.1][965d06f4][ExtensionHostConnection] New connection established.
[09:52:23] [127.0.0.1][965d06f4][ExtensionHostConnection] <2128> Launched Extension Host Process.
rejected promise not handled within 1 second: Error: Could not find pty with id "7"
stack trace: Error: Could not find pty with id "7",    at r._throwIfNoPty (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:17:5354),    at r.updateTitle (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:17:1694),    at Object.call (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:13:8364),    at L.onPromise (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:12:4938),    at L.onRawMessage (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:12:4297),    at /home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:12:3553,    at D.fire (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:8:1712),    at process.N (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:6:33914),    at process.emit (events.js:315:20),    at emit (internal/child_process.js:903:12),    at processTicksAndRejections (internal/process/task_queues.js:81:21)
[Error: Could not find pty with id "7",    at r._throwIfNoPty (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:17:5354),    at r.updateTitle (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:17:1694),    at Object.call (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:13:8364),    at L.onPromise (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:12:4938),    at L.onRawMessage (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:12:4297),    at /home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:12:3553,    at D.fire (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:8:1712),    at process.N (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:6:33914),    at process.emit (events.js:315:20),    at emit (internal/child_process.js:903:12),    at processTicksAndRejections (internal/process/task_queues.js:81:21)]
New EH opened, aborting shutdown
[09:57:22] New EH opened, aborting shutdown
[14:56:18] [127.0.0.1][2526b347][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[14:56:19] [127.0.0.1][965d06f4][ExtensionHostConnection] <2128> Extension Host Process exited with code: 0, signal: null.
Last EH closed, waiting before shutting down
[14:56:19] Last EH closed, waiting before shutting down
Got delay-shutdown request while in shutdown timeout, delaying
[14:56:45] Got delay-shutdown request while in shutdown timeout, delaying
Cancelling previous shutdown timeout
[14:56:45] Cancelling previous shutdown timeout
[14:56:46] [127.0.0.1][aaef2aab][ManagementConnection] New connection established.
[14:56:46] [127.0.0.1][c7c8aab5][ExtensionHostConnection] New connection established.
[14:56:46] [127.0.0.1][c7c8aab5][ExtensionHostConnection] <66620> Launched Extension Host Process.
rejected promise not handled within 1 second: Error: Could not find pty with id "22"
stack trace: Error: Could not find pty with id "22",    at r._throwIfNoPty (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:17:5354),    at r.updateTitle (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:17:1694),    at Object.call (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:13:8364),    at L.onPromise (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:12:4938),    at L.onRawMessage (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:12:4297),    at /home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:12:3553,    at D.fire (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:8:1712),    at process.N (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:6:33914),    at process.emit (events.js:315:20),    at emit (internal/child_process.js:903:12),    at processTicksAndRejections (internal/process/task_queues.js:81:21)
[Error: Could not find pty with id "22",    at r._throwIfNoPty (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:17:5354),    at r.updateTitle (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:17:1694),    at Object.call (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:13:8364),    at L.onPromise (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:12:4938),    at L.onRawMessage (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:12:4297),    at /home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:12:3553,    at D.fire (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:8:1712),    at process.N (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:6:33914),    at process.emit (events.js:315:20),    at emit (internal/child_process.js:903:12),    at processTicksAndRejections (internal/process/task_queues.js:81:21)]
rejected promise not handled within 1 second: Error: Could not find pty with id "22"
stack trace: Error: Could not find pty with id "22",    at r._throwIfNoPty (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:17:5354),    at r.updateIcon (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:17:1754),    at Object.call (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:13:8364),    at L.onPromise (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:12:4938),    at L.onRawMessage (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:12:4297),    at /home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:12:3553,    at D.fire (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:8:1712),    at process.N (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:6:33914),    at process.emit (events.js:315:20),    at emit (internal/child_process.js:903:12),    at processTicksAndRejections (internal/process/task_queues.js:81:21)
[Error: Could not find pty with id "22",    at r._throwIfNoPty (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:17:5354),    at r.updateIcon (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:17:1754),    at Object.call (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:13:8364),    at L.onPromise (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:12:4938),    at L.onRawMessage (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:12:4297),    at /home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:12:3553,    at D.fire (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:8:1712),    at process.N (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:6:33914),    at process.emit (events.js:315:20),    at emit (internal/child_process.js:903:12),    at processTicksAndRejections (internal/process/task_queues.js:81:21)]
[IPC Library: Pty Host]  INFO Persistent process "20": Replaying 6825 chars and 1 size events
rejected promise not handled within 1 second: Error: Could not find pty with id "24"
stack trace: Error: Could not find pty with id "24",    at r._throwIfNoPty (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:17:5354),    at r.updateTitle (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:17:1694),    at Object.call (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:13:8364),    at L.onPromise (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:12:4938),    at L.onRawMessage (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:12:4297),    at /home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:12:3553,    at D.fire (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:8:1712),    at process.N (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:6:33914),    at process.emit (events.js:315:20),    at emit (internal/child_process.js:903:12),    at processTicksAndRejections (internal/process/task_queues.js:81:21)
[Error: Could not find pty with id "24",    at r._throwIfNoPty (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:17:5354),    at r.updateTitle (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:17:1694),    at Object.call (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:13:8364),    at L.onPromise (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:12:4938),    at L.onRawMessage (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:12:4297),    at /home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:12:3553,    at D.fire (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:8:1712),    at process.N (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:6:33914),    at process.emit (events.js:315:20),    at emit (internal/child_process.js:903:12),    at processTicksAndRejections (internal/process/task_queues.js:81:21)]
rejected promise not handled within 1 second: Error: Could not find pty with id "24"
stack trace: Error: Could not find pty with id "24",    at r._throwIfNoPty (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:17:5354),    at r.updateIcon (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:17:1754),    at Object.call (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:13:8364),    at L.onPromise (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:12:4938),    at L.onRawMessage (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:12:4297),    at /home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:12:3553,    at D.fire (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:8:1712),    at process.N (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:6:33914),    at process.emit (events.js:315:20),    at emit (internal/child_process.js:903:12),    at processTicksAndRejections (internal/process/task_queues.js:81:21)
[Error: Could not find pty with id "24",    at r._throwIfNoPty (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:17:5354),    at r.updateIcon (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:17:1754),    at Object.call (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:13:8364),    at L.onPromise (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:12:4938),    at L.onRawMessage (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:12:4297),    at /home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:12:3553,    at D.fire (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:8:1712),    at process.N (/home/kylelamberton1/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/platform/terminal/node/ptyHostMain.js:6:33914),    at process.emit (events.js:315:20),    at emit (internal/child_process.js:903:12),    at processTicksAndRejections (internal/process/task_queues.js:81:21)]
[14:58:07] [127.0.0.1][aaef2aab][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[14:58:07] [127.0.0.1][c7c8aab5][ExtensionHostConnection] <66620> Extension Host Process exited with code: 0, signal: null.
Cancelling previous shutdown timeout
[14:58:07] Cancelling previous shutdown timeout
Last EH closed, waiting before shutting down
[14:58:07] Last EH closed, waiting before shutting down
Last EH closed, shutting down
[15:03:07] Last EH closed, shutting down
